language: php
 
sudo: true
 
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
 
sudo: false
 
matrix:
  fast_finish: true
 
  allow_failures:
    - php: hhvm
 
cache:
  directories:
    - laravel #only cache the laravel directory
 
services: mysql
 
install:
  # create a new database for the hyn connection
  - export DB_USERNAME=travis DB_DATABASE=hms DB_PASSWORD= QUEUE_DRIVER=sync
  #run the setup script
  - curl -s https://github.com/MohamedSeliem/hms/blob/master/setup.sh
