language: php 
sudo: true 
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

cache:
  directories:
  - laravel #only cache the laravel directory

services: mysql

before_script:
  -"composer install"
script:
  -chmod +x testrunner
  -/testrunner